earthowned/planetfarms

.gitignore, api/config/config.json, api/config/database.js, api/controllers/userController.js, api/migrations/20210407172155-User.js, api/migrations/20210408073734-Resource.js, api/models/index.js, api/models/userModel.js, api/package.json, api/routes/userRouter.js, api/seeders/20210407155407-User.js, api/seeders/20210408101935-resources.js, api/server.js, api/utils/generateToken.js, docker-compose.yml
Fixes: #9 
Set up
1. Express
2. PostgreSQL
3. Sequelize ORM
=> node express and postgresql (fixes #9)

src/App.css, src/Components/GroupModal/group-modal.css, src/Components/NewAddModal/news-add-modal.css, src/Components/NewsCard/NewsCard.jsx, src/Components/NewsCard/news-card.css, src/Screens/CommunityMemberProfile/community-member-profile.css, src/Screens/CommunityNews/CommunityNews.jsx, src/Screens/CommunityNews/community-news.css
=> better layout (fixes #36)

src/Components/Button/button.css, src/Components/Input/InputComponent.jsx, src/Components/Input/input-component.css, src/Components/Logo/logo.css, src/Screens/Congratulation/CongratulationScreen.jsx, src/Screens/Congratulation/congratulation-screen.css, src/Screens/Login/LoginScreen.jsx, src/Screens/Login/login-screen.css, src/Screens/SignUp/SignupScreen.jsx, src/Screens/SignUp/signup-screen.css
issues: #42, #10 
I have made the screens responsive as well.
=> improved login responsiveness (fixes #42)(fixes #10)

.gitignore, api/controllers/resourceController.js, api/models/resourceModel.js, api/routes/resourceRouter.js, api/routes/userRouter.js, api/server.js
issue: #37
api: `/api/resources` parameter `pageNumber` default pageNumber is 1
=> create resources api (fixes #37)

api/package.json, api/server.js
CORS is a node.js package for providing a Connect/Express middleware that can be used to enable CORS with various options.
Made new PR since its backend change but please merge it before using #60.
=> api: cors added

api/controllers/courseController.js, api/controllers/resourceController.js
=> api: case insensitive search (fixes #56)

src/App.css, src/Components/Sidebar/sidebar.css, src/Layout/DashboardLayout/DashboardLayout.jsx, src/Screens/CommunityNewsView/community-news-view.css, src/Screens/Login/login-screen.css, src/Screens/SignUp/signup-screen.css
i have the login sign up and community-view-page tablet size
=> responsive login signup and community news (fixes #66)

README.md
=> update README.md (fixes #64)

src/Components/CollectionModal/CollectionModal.jsx, src/Screens/Library/Library.jsx, src/actions/resourceActions.js
=> fix resource create from misbehave 

src/Components/MyCoursesCard/MyCoursesCard.jsx, src/Components/MyCoursesCard/my-courses-card.css, src/Layout/DashboardLayout/dashboard.css, src/Screens/Dashboard/MyCourses.jsx, src/Screens/Dashboard/my-courses.css
=> responsive mycourses (fixes #101)

src/Layout/DashboardLayout/DashboardLayout.jsx, src/Layout/DashboardLayout/dashboard.css
=> menu mobile improve click functionality (fixes #94)

src/Components/Sidebar/Sidebar.jsx
I also have refactored the sidebar code, now it's dynamic.
=> menu logo refactor (fixes #152)

src/App.css, src/Components/Sidebar/sidebar.css
I also have resized the sidebar icons to 32px as per the figma design, which was previously 45px. 
Is it ok or not?
=> menu css enhancements  (fixes #170)

src/Components/CollectionModal/CollectionModal.jsx, src/Components/CollectionModal/collection-modal.css, src/Components/CoursesHeader/CoursesHeader.jsx, src/Components/EnterprisesCollection/enterprises-collection.css, src/Components/GroupModal/GroupModal.jsx, src/Components/GroupModal/group-modal.css, src/Components/GroupUsers/GroupUsers.jsx, src/Components/GroupUsers/group-users.css, src/Components/MessageRightComponent/MessageRightComponent.jsx, src/Components/MobileMessage/MobileMessage.jsx, src/Components/SimpleFilter/SimpleFilter.jsx, src/Components/SimpleFilter/simple-filter.css, src/Components/SimpleModal/SimpleModal.jsx, src/Components/SimpleModal/simple-modal.css, src/Screens/Courses/Courses.jsx, src/constants/sampleData.js
I have used the modal component in this screen. I also have made all the modal used in this screen responsive.
=> courses add collection dialog (fixes #202)

src/Components/MessageDropdown/message-dropdown.css, src/Components/Sidebar/sidebar.css, src/Layout/DashboardLayout/DashboardLayout.jsx, src/Layout/DashboardLayout/dashboard.css
The corresponding pr of this pr can be closed
=> menu refactor mobile (fixes #215)

src/Components/MessengerMain/MessengerMain.jsx, src/Components/MessengerMain/messenger-main.css, src/Components/SearchComponent/SearchComponent.jsx
I also have resolved this issue.
=> messages improved (fixes #229)

src/Components/DragDrop/DragDrop.jsx, src/Components/EnterprisesCollection/enterprises-collection.css, src/Components/NewAddModal/news-add-modal.css, src/Components/NewsCreateModal/news-create-modal.css, src/Screens/CommunityNews/NewsAdd/news-add.css, src/Screens/CommunityNewsView/CommunityNewsView.jsx, src/Screens/CommunityNewsView/community-news-view.css, src/Screens/CourseManager/AddLesson/AddLesson.jsx
I have also  designed the drag and drop as per the figma's design.
=> upload redesign (fixes #227)

src/components/button/Button.jsx, src/components/button/Button.scss, src/components/input/Input.jsx, src/screens/forgotPassword/ForgotPassword.jsx
=> login: forgot password (fixes #284)

api/package.json, api/src/controllers/resizerController.js, api/src/controllers/resourceController.js, api/src/helpers/filehelpers.js, api/src/routes/resizerRouter.js, api/src/routes/resourceRouter.js, api/src/server.js, src/components/listView/ListView.jsx
=> api: image format webp

src/screens/communityMembers/CommunityMembers.jsx
=> member page dashboard

.github/workflows/erdiagram.yml
=> manual workflow for ER diagrams

README.md, docker-compose.yml
=> pgadmin4 docker

api/src/controllers/communityController.js, api/src/controllers/userController.js, api/src/middleware/authMiddleware.js, src/actions/userAction.js
=> local login authentication

api/src/controllers/communityController.js, api/src/controllers/materialController.js, api/src/controllers/userController.js, api/src/models/materialModel.js, src/actions/materialActions.js, src/components/dragDrop/DragDrop.jsx, src/components/material/Material.jsx, src/components/material/Material.scss, src/screens/courseManager/addLesson/AddLesson.jsx, src/screens/courseManager/addLesson/AddLesson.scss, src/screens/courseManager/addLesson/addMaterial.js, src/screens/courseManager/editLesson/EditLesson.jsx, src/screens/dashboard/lessonPage/LessonPage.jsx, src/screens/dashboard/lessonPage/LessonPage.scss
=> lesson materials (fixes #297)

api/src/controllers/communityController.js, api/src/middleware/authMiddleware.js, src/actions/communityActions.js, src/actions/communityGroupActions.js, src/actions/enterpriseAction.js, src/actions/memberActions.js, src/actions/newsActions.js, src/actions/resourceActions.js, src/actions/userAction.js, src/components/settingsActionModal/SettingsActionModal.jsx, src/screens/login/LoginScreen.jsx, src/utils/apiFunc.jsx
=> expired session redirect to login

src/actions/courseActions.js, src/components/courseCreateModal/newCourseCreateModal/NewCourseCreateModal.jsx, src/components/coursesCard/AddCollection.jsx, src/components/coursesCard/CardContent.jsx, src/components/coursesCard/CoursesCard.jsx, src/components/coursesCard/EnrollContainer.jsx, src/components/coursesCard/Star.jsx, src/screens/courses/Courses.jsx
=> Course creator (connects #307)

.github/workflows/gpio.yml, .github/workflows/ssh.yml
Fixes #318 
SSH to GPIO using a manual deploy with GitHub Actions.
=> workflow to deploy on GPIO (fixes #318)

README.md, api/src/migrations/20210627152703-alter-table-lessons-remove-column-steps.js, api/src/seeders/20210608081218-communities.js, api/src/seeders/20210615104502-categories.js
=> default seed for initialization

api/src/controllers/lessonController.js, api/src/migrations/20210717060216-alter-table-lessons-add-column-order.js, api/src/models/lessonModel.js, src/actions/lessonActions.js, src/actions/userAction.js, src/components/courseCreateModal/CourseCreateModal.scss, src/components/courseCreateModal/newCourseCreateModal/NewCourseCreateModal.jsx, src/components/courseCreateModal/newCourseCreateModal/NewCourseCreateModal.scss, src/components/coursesCard/CoursesCard.scss, src/components/dragDrop/DragDrop.jsx, src/components/filter/Filter.jsx, src/components/filter/Filter.scss, src/components/myCoursesCard/courseDescription/LessonCourse.jsx, src/components/myCoursesCard/courseDescription/LessonCourseSingle.jsx, src/components/newsCreateModal/NewsCreateModal.scss, src/screens/courseManager/addLesson/AddContent.jsx, src/screens/courseManager/addLesson/AddLesson.jsx, src/screens/courseManager/addLesson/AddLesson.scss, src/screens/courseManager/adminCoursePage/LessonBlock.jsx, src/screens/courseManager/editLesson/EditLesson.jsx
=> ordering of lesson

src/screens/communitySwitching/CommunitySwitching.jsx
Fixes #338
ToggleSwitch component is used in community switch add modal
http://localhost:3000/community-switching/all-communities
=> toggle switch (fixes #338)

src/components/listView/ListView.jsx, src/components/listView/ListView.scss, src/components/pagination/Pagination.css, src/components/pagination/Pagination.jsx
Fixes #328 
pagination design is fixed
text of the list view is fixed
Previously:
Now: 
http://localhost:3000/library
=> library pagination mobile view (fixes #328)

.github/workflows/manualinstallapi.yml
Fixes #357
Created a workflow to notify the user if the api db inits correctly on a fresh install.
=> workflow: db initalize test (fixes #357)

src/App.jsx, src/actions/userAction.js, src/components/signInSignUp/SignUp.jsx, src/screens/congratulation/Congratulation.scss, src/screens/congratulation/CongratulationScreen.jsx, src/screens/dashboard/MyProfile.jsx
- redirect to home page after completing the sign up
- changed route of edit information page to /edit-information from /register-complete
- changed edit information layout to dashboard layout
- made DOB optional
- logout if api not accessible #363
=> profile edit

api/src/controllers/testController.js, api/src/controllers/userTestController.js, api/src/routes/userTestRouter.js, src/App.jsx, src/actions/testActions.js, src/screens/addTest/AddTest.jsx, src/screens/addTest/AddTest.scss, src/screens/dashboard/lessonPage/LessonTest.jsx, src/screens/lessonTestPage/LessonTestPage.jsx, src/screens/lessonTestPage/LessonTestPage.scss
Fixes #372 
Back button is now working
changed user test api
changed the api call from lessonTest.jsx
changeg test edit api(test controller)
api/src/controllers/userTestController.js
api/src/routes/userTestRouter.js
src/screens/dashboard/lessonPage/LessonTest.jsx
src/screens/lessonTestPage/LessonTestPage.jsx
api/src/controllers/testController.js
src/screens/addTest/AddTest.jsx
=> take test (fixes #372)

api/src/migrations/20210726102757-alter-questions-constraint.js
Fixes #384
Added the migration file: alter-questions-constraint to remove unique constraint
src/migrations/20210726102757-alter-questions-constraint.js
=> remove unique question constraint (fixes #384)

src/screens/communitySwitching/CommunitySwitching.jsx
Fixes #378 
Removed community header
Added subheader component instead
http://localhost:3000/community-switching/all-communities
src/screens/communitySwitching/CommunitySwitching.jsx
=> community subheader (fixes #378)

api/src/controllers/communityUserController.js, api/src/controllers/userController.js, src/components/cardImage/CardImage.jsx, src/components/cardImage/CardImage.scss, src/screens/communityMemberProfile/CommunityMemberProfile.jsx
Fixes ##389
changed user controller to get the accurate info for the community member profile
removed email from from community member page
back button of community member profile works now
http://localhost:3000/community-members/calendar_ui_form
http://localhost:3000/community-members-profile/1
file changed:
src/controllers/communityUserController.js
src/controllers/userController.js
../src/components/cardImage/CardImage.jsx
../src/components/cardImage/CardImage.scss
../src/screens/communityMemberProfile/CommunityMemberProfile.jsx
=> community members (fixes #389)

api/src/helpers/filehelpers.js
Removed original name of image while uploading
http://localhost:8080/:filepath
=> Removed original name of image while uploading

.github/workflows/dpio.yml
=> adding manual workflow for dpio

src/components/header/HeaderComponent.jsx, src/components/header/ProfileMenu.jsx, src/components/messageDropdown/MessageDropdown.jsx, src/components/messageDropdown/MessageDropdown.scss, src/components/messengerMain/MessengerMain.scss, src/components/settingsActionModal/SettingsActionModal.scss, src/layout/dashboardLayout/DashboardLayout.jsx
Fixes #327 
dropdown added to the mobile view
responsive mobile view: dropdown and logout modal
modified file:
src/layout/dashboardLayout/DashboardLayout.jsx
src/components/settingsActionModal/SettingsActionModal.scss
src/components/messageDropdown/MessageDropdown.jsx
src/components/messengerMain/MessengerMain.scss
=> mobile view dropdown menu (fixes #327)

api/src/migrations/20210407172155-User.js, api/src/migrations/20210408073734-Resource.js, api/src/migrations/20210412094134-Courses.js, api/src/migrations/20210429091017-Collection.js, api/src/migrations/20210430073336-create_community_news.js, api/src/migrations/20210503090246-Enterprises.js, api/src/migrations/20210507082739-CommunityGroup.js, api/src/migrations/20210514073023-Calendar.js, api/src/migrations/20210518053856-alter_group_migration.js, api/src/migrations/20210518055321-alter_enterprise_migration.js, api/src/migrations/20210518060315-alter_enterprise_migration.js, api/src/migrations/20210615104008-create-table-category.js, api/src/migrations/20210617083940-alter-table-courses-add-column-thumbnail.js, api/src/migrations/20210617100833-alter-table-Courses-add-column-price.js, api/src/migrations/20210617102549-alter-table-Courses-add-column-category.js, api/src/migrations/20210621090533-alter-table-courses-add-column-isFree.js, api/src/migrations/20210621105412-alter-table-courses-add-column-courseId.js, api/src/migrations/20210621170218-create-table-lessons.js, api/src/migrations/20210627151759-alter-table-courses-remove-column-courseId.js, api/src/migrations/20210627162502-alter-table-lessons-remove-column-lessonId.js, api/src/migrations/20210701061554-alter-table-lessonPhotos-add-column-lessonImg.js, api/src/migrations/20210701084131-alter-table-lessonPhotos-add-column-isImgDesc.js, api/src/migrations/20210702120020-alter-table-materials-add-column-materialName.js, api/src/migrations/20210712080126-alter-table-lessons-add-column-lessonDesc.js, api/src/migrations/20210717060216-alter-table-lessons-add-column-order.js, api/src/migrations/20210720165840-alter-table-enrolls-add-column-remove_enroll_courseId_unique_key.js, api/src/migrations/20210721075249-alter-user-table.js, api/src/migrations/20210726115631-alter_users_add_role.js
Fixes #430
Add await to migrations queries
=> added await to migrations (fixes #430)

api/src/middleware/authMiddleware.js, src/actions/userAction.js
Fixes #437
changed the user Action and auth file
=> user registration error (fixes #437)

public/index.html
Fixes #442
Adding the type attribute to the script tag will erase the unexpected token error.
=> script tag attribute (fixes #442)

api/src/migrations/20210721075249-alter-user-table.js
=> fix migration db (fixes #452)(fixes  #453)

.eslintrc.js, package.json
Create eslint config for frontend project
=> eslint config

src/components/button/Button.scss, src/components/checkbox/Checkbox.jsx, src/components/oAuthBtn/OAuthBtn.scss, src/components/signInSignUp/SignIn.jsx, src/components/signInSignUp/SignInSignUp.scss, src/index.css
=> login screen fonts

.github/workflows/builder.yml
=> docker build with node 14.x (fixes #470)

public/index.html, src/common/navigation/styles.scss, src/common/page-header/index.jsx, src/common/page-header/mobile-menu/styles.scss, src/common/side-bar-navigation/index.jsx, src/constants/enums.js, src/hooks/index.js, src/hooks/useDeviceType.js, src/layout/auth/styles.scss, src/layout/dashboard/styles.scss, src/scss/_mixins.scss, src/scss/_variables.scss
1. implement use device hook;
2. handle screen orientation;
3. handle safe area insets for mobile browsers;
=> fix mobile / tablet layout depend on orientation

api/src/controllers/newsController.js, api/src/migrations/20220313023237-news_category.js, api/src/models/newsModel.js, api/src/routes/newsRouter.js
news api update
Reference #494
=> add filters and attributes on api (#495) (connects #493)

api/src/controllers/newsController.js, api/src/routes/newsRouter.js
Remove community word from routes
Add protect to get logged in user details
=> api news route update (connects#493)

api/src/models/newsModel.js, src/actions/newsActions.js, src/api/news.js, src/common/avatar/styles.scss, src/common/containers/news-container/news-item/helpers.js, src/common/containers/news-container/news-item/index.jsx, src/screens/communityNews/newsAdd/NewsAdd.jsx, src/screens/news/news-list/index.jsx
=> integrate news add

api/src/controllers/courseController.js
- Filters
- Search
- Sorting
- Member count
=> course get api
